GET http://localhost:3000/users

###
GET http://localhost:3000/users/1

###
POST http://localhost:3000/users
content-Type:application/json

{
    "name":"Istiqomh",
    "email":"istiqomahi099@gmail.com",
    "gender":"male"
}

###
PATCH http://localhost:3000/users/1
content-Type:application/json

{
    "name":"Alan Susanto",
    "email":"AlanHertantog@gmail.com",
    "gender":"Laki-Laki"
}

###
DELETE http://localhost:3000/users/2